# Site settings
title: Kimetrica Wiki
email: melissa.earl@kimetrica.com
description: > # this means to ignore newlines until "baseurl:"
 For all your Kimetrica code dumping needs!
baseurl: "/Kimetrica-Wiki" 
url: "localhost:4000"
github_username:  melissa-earl

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
